apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: notify
  namespace: tekton-pipelines
spec:
  params:
  - name: message
    type: string
  steps:
  - computeResources: {}
    image: alpine:3.19
    name: echo
    script: |
      echo "$(params.message)"
